package View;


import Modelo.TabelaToken;
import Modelo.Token;
import Modelo.NumeroLinhas;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import controlo.Validacoes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 
 */
public class TelaPrincipal extends javax.swing.JFrame {
      private String[] colunas = {"Token","Classe","Linha"};
      private ArrayList<Token> lin;
      TabelaToken modelo;
       Validacoes classificar;
       private JFileChooser fc = new JFileChooser();
    
    public TelaPrincipal() {
        initComponents();
        classificar=new Validacoes();
        lin=new ArrayList<>();
        modelo=new TabelaToken(lin, colunas);
        setLocationRelativeTo(null);
        jTextArea1.setBorder(new NumeroLinhas());
         TableCellRenderer renderer = new EvenOddRenderer();
        jTable1.setDefaultRenderer(Object.class, renderer);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code.- The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jtfMostrarLinha = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnCorrer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfBug = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador-EAMMT");
        setBackground(new java.awt.Color(255, 255, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jtfMostrarLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMostrarLinhaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-salvar-filled-50.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAbrir.setBackground(new java.awt.Color(255, 255, 255));
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-abrir-pasta-50 (1).png"))); // NOI18N
        btnAbrir.setToolTipText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-vassoura-50.png"))); // NOI18N
        btnLimpar.setToolTipText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCorrer.setBackground(new java.awt.Color(255, 255, 255));
        btnCorrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/compil.png"))); // NOI18N
        btnCorrer.setToolTipText("Verificar");
        btnCorrer.setMaximumSize(new java.awt.Dimension(41, 41));
        btnCorrer.setMinimumSize(new java.awt.Dimension(41, 41));
        btnCorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnCorrer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(454, 454, 454))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCorrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 51));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Token", "Classe", "Linha"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel1.setText("LINHA");

        jtfBug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBugActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel2.setText("ERRO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfBug)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtfMostrarLinha))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfMostrarLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfMostrarLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMostrarLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMostrarLinhaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
            salvar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrerActionPerformed
     if (!jTextArea1.getText().isEmpty()){
                jTable1.removeAll();
                modelo.removeall();
                array();
                jTable1.setModel(modelo);
                 jTable1.setVisible(true);
     } else{
        JOptionPane.showMessageDialog(null, "Por favor introduza algum texto!!","ACESSO NEGADO",JOptionPane.ERROR_MESSAGE);
     }

    }//GEN-LAST:event_btnCorrerActionPerformed
private void clean(){
    jTextArea1.setText("");
    jtfMostrarLinha.setText("");
    jtfBug.setText("");
    jTable1.removeAll();
    jTable1.setVisible(false);
   
    
    
    
}
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        clean();
    }//GEN-LAST:event_btnLimparActionPerformed

    
    
    
    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
    }//GEN-LAST:event_jTextArea1KeyTyped

   
    public void array(){
        
       String texto=jTextArea1.getText();
       int posicao=0;
       modelo.removeall();
       if(texto.length()>0){
       String[] textosplit;
          textosplit = texto.split("\n");
          
        
         for(int i=0; i<textosplit.length;i++){
             String textoposix=textosplit[i];
             String [] lista=textoposix.split(" ");
             
                 for(int k=0;k<lista.length;k++){
                     posicao=posicao+lista[k].length()+1;
                     Token token=new Token(validar(lista[k]), lista[k],i+1,posicao);
                     modelo.addlinha(token);
                    
                 
             }
         }
    }
       else{
           jTable1.removeAll();
       jTable1.clearSelection();
       }
       
    }
    
     public void salvar() {
if (fc.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
        return;
    }

    PrintWriter pw = null;
    try {
        pw = new PrintWriter(fc.getSelectedFile());
        Scanner scan = new Scanner(jTextArea1.getText());
        while (scan.hasNextLine()) {
            pw.print(scan.nextLine());

            
            if (scan.hasNextLine()) 
                pw.println();
        }
        pw.flush();
        JOptionPane.showMessageDialog(this, "Gravado com Sucesso");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Não foi possível salvar o arquivo.");
        e.printStackTrace();
    } finally {
        if (pw != null) {
            pw.close();
        }
    }
    }
    
    public String validar(String lexema){
        return classificar.validar(lexema);
    }
    
   
    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
    }//GEN-LAST:event_jTextArea1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 int posicao=modelo.gettoken(jTable1.getSelectedRow()).getPosicao();
  Color foreground, background;
        
        if(modelo.getValueAt(jTable1.getSelectedRow(), 1).toString()=="Indefinido"){
            jTextArea1.requestFocusInWindow();
            jTextArea1.setCaretPosition(posicao);
            jtfMostrarLinha.setText(modelo.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jtfBug.setText(modelo.getValueAt(jTable1.getSelectedRow(), 0).toString());
        }else{
            jTextArea1.requestFocusInWindow();
            jTextArea1.setCaretPosition(posicao);// TODO add your handling code here:
            jtfMostrarLinha.setText(modelo.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jtfBug.setText("");
        }
         
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
if (fc.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
        return;
    }
    jTextArea1.setText(fc.getSelectedFile().getAbsolutePath());

    StringBuilder texto = new StringBuilder();
    try {
        Scanner scan = new Scanner(fc.getSelectedFile());
        while (scan.hasNextLine()) {
            texto.append(scan.nextLine()).append("\n");
        }

        jTextArea1.setText(texto.toString());
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Não foi possível ler o arquivo solicitado.");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void jtfBugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBugActionPerformed

    private boolean inicio(){
       String inicio=jTextArea1.getText();
       String princio=inicio.substring(0, 7);
        System.out.println(princio);
       if(princio.equalsIgnoreCase("program"))
            return true;
       else
           return false;
        
        
       
    }
       class EvenOddRenderer implements TableCellRenderer {

    public final DefaultTableCellRenderer DEFAULT_RENDERER = new DefaultTableCellRenderer();
  Token token;
       
    public List<Token> list;

    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component renderer = DEFAULT_RENDERER.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

        Color foreground, background;
        this.list = modelo.getLinhas();
        
        if (isSelected) {
            foreground = Color.WHITE;
            background = new Color(153,153,153);
        } else {
            if (this.list.get(row).getClasse().equals("Indefinido")) {
                foreground = Color.BLACK;
                background = new  Color(255,102,0);
            } else {
                foreground = Color.BLACK;
                background = new Color(255,255,255);
            }
        }
        renderer.setForeground(foreground);
        renderer.setBackground(background);
        return renderer;
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //Layout de telas
             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCorrer;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jtfBug;
    private javax.swing.JTextField jtfMostrarLinha;
    // End of variables declaration//GEN-END:variables
}
